### ISSUE TITLE
CSRF token mismatch错误

### ISSUE THREAD

**Issue by dmblock** [pterodactyl-china/panel#51]
### Current Behavior

在没有SSL的情况下，用数字IP访问，登录面板会报错CSRF token mismatch

### Expected Behavior

CSRF token mismatch

### Steps to Reproduce

希望有人能帮我解决问题，感谢

### Panel Version

1.4.0

### Wings Version

1.4.2

### Error Logs

```bash
http://bin.ptdl.co/pctdy
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [x] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by vlssu** [comment]
你用的版本是Panel:1.4.0、Wings:1.4.2，这些版本我并未进行优化处理，因此你用的不是我们构建的版本，所以你应该在  https://github.com/pterodactyl/panel/issues 发帖

**Comment by vlssu** [comment]
因为你并未用我们的版本所以在上次的回答中我未看日志进行回答的，内容有误。但依然建议你升级版本，因为你的版本实在太低了。我也相信 pterodactyl 那不会处理你发出的请求。
