### ISSUE TITLE
Server Internal Error 500 for database resources

### ISSUE THREAD

**Issue by KenRen98** [pterodactyl-china/panel#57]
### Current Behavior

![image](https://github.com/pterodactyl-china/panel/assets/81537377/27cfc651-3a12-4825-bde9-8983efaf2b5a)
All Servers in database page now shows this. No meaningful info in Chrom Dev tool.

Note: I did not setup any database for the servers.

### Expected Behavior

No Server Error 500 showing

### Steps to Reproduce

After Update Panel Version from 1.11.2.0 to 1.11.4.0, I followed update procedure in the docs you guys provided.

### Panel Version

1.11.4.0

### Wings Version

1.11.8.0

### Games and/or Eggs Affected

N/A

### Docker Image

N/A

### Error Logs

```bash
Wings: https://ptero.co/nyqysotuba

Panel: https://pteropaste.com/87ff4zkvt2n4
More: https://pteropaste.com/0rkz18qpovx3/ (After Refresh the Database Page <if Help>)
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by KenRen98** [comment]
不会PHP，看不懂log，chrome dev tool只提示500.

**Comment by KenRen98** [comment]
之前的1.11.3的时候是没有这个bug的，应该是从1.11.3更新来的

**Comment by KenRen98** [comment]
PHP版本和Artisan版本：
![image](https://github.com/pterodactyl-china/panel/assets/81537377/add389b4-3a31-4e58-857f-8bd4419531e4)

**Comment by KenRen98** [comment]
/app/app/Providers # cat HashidsServiceProvider.php
<?php

namespace Pterodactyl\Providers;

use Pterodactyl\Extensions\Hashids;
use Illuminate\Support\ServiceProvider;
use Pterodactyl\Contracts\Extensions\HashidsInterface;

class HashidsServiceProvider extends ServiceProvider
{
    /**
     * Register the ability to use Hashids.
     */
    public function register(): void
    {
        $this->app->singleton(HashidsInterface::class, function () {
            /** @var \Illuminate\Contracts\Config\Repository $config */
            $config = $this->app['config'];

            return new Hashids(
                $config->get('hashids.salt', ''),
                $config->get('hashids.length', 0),
                $config->get('hashids.alphabet', 'abcdefghijkmlnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890')
            );
        });

        $this->app->alias(HashidsInterface::class, 'hashids');
    }
}
/app/app/Providers #

**Comment by KenRen98** [comment]
`/app/app/Providers # cat HashidsServiceProvider.php
<?php

namespace Pterodactyl\Providers;

use Pterodactyl\Extensions\Hashids;
use Illuminate\Support\ServiceProvider;
use Pterodactyl\Contracts\Extensions\HashidsInterface;

class HashidsServiceProvider extends ServiceProvider
{
    /**
     * Register the ability to use Hashids.
     */
    public function register(): void
    {
        $this->app->singleton(HashidsInterface::class, function () {
            /** @var \Illuminate\Contracts\Config\Repository $config */
            $config = $this->app['config'];

            return new Hashids(
                $config->get('hashids.salt', ''),
                $config->get('hashids.length', 0),
                $config->get('hashids.alphabet', 'abcdefghijkmlnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890')
            );
        });

        $this->app->alias(HashidsInterface::class, 'hashids');
    }
}
/app/app/Providers # `

**Comment by KenRen98** [comment]
``
/app/app/Providers # cat HashidsServiceProvider.php
<?php

namespace Pterodactyl\Providers;

use Pterodactyl\Extensions\Hashids;
use Illuminate\Support\ServiceProvider;
use Pterodactyl\Contracts\Extensions\HashidsInterface;

class HashidsServiceProvider extends ServiceProvider
{
    /**
     * Register the ability to use Hashids.
     */
    public function register(): void
    {
        $this->app->singleton(HashidsInterface::class, function () {
            /** @var \Illuminate\Contracts\Config\Repository $config */
            $config = $this->app['config'];

            return new Hashids(
                $config->get('hashids.salt', ''),
                $config->get('hashids.length', 0),
                $config->get('hashids.alphabet', 'abcdefghijkmlnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890')
            );
        });

        $this->app->alias(HashidsInterface::class, 'hashids');
    }
}
/app/app/Providers #

**Comment by KenRen98** [comment]
`PHP`
/app/app/Providers # cat HashidsServiceProvider.php
<?php

namespace Pterodactyl\Providers;

use Pterodactyl\Extensions\Hashids;
use Illuminate\Support\ServiceProvider;
use Pterodactyl\Contracts\Extensions\HashidsInterface;

class HashidsServiceProvider extends ServiceProvider
{
    /**
     * Register the ability to use Hashids.
     */
    public function register(): void
    {
        $this->app->singleton(HashidsInterface::class, function () {
            /** @var \Illuminate\Contracts\Config\Repository $config */
            $config = $this->app['config'];

            return new Hashids(
                $config->get('hashids.salt', ''),
                $config->get('hashids.length', 0),
                $config->get('hashids.alphabet', 'abcdefghijkmlnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890')
            );
        });

        $this->app->alias(HashidsInterface::class, 'hashids');
    }
}
/app/app/Providers #

**Comment by KenRen98** [comment]
试了下，数据库创建等部分操作仍然是可以正常运行的，但始终无法避免顶上的500。看了下HashidsProvide里面salt是''。

**Comment by vlssu** [comment]
我这无法复现出此问题，查看面板的权限设置，比如宝塔是 755/www。（因宝塔的设计原因，请直接修改权限，因为你看到的可能并不是你看到。）
或者尝试保留`.env`文件后，依照文档按照新搭建的流程来搭建，然后再通过覆盖原有`.env`文件。
（一切操作都有风险，请在备份后再进行操作）

**Comment by KenRen98** [comment]
没事了，手动在var/env里面加入了salt的env设置后

```.env
HASHIDS_SALT=YourSaltStringHere
HASHIDS_LENGTH=8
HASHIDS_ALPHABET=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890
```



本来以为这里PHP code的意思是默认设置为‘’
```PHP provider
/app/app # cd Providers/
/app/app/Providers # cat HashidsServiceProvider.php 
<?php

namespace Pterodactyl\Providers;

use Pterodactyl\Extensions\Hashids;
use Illuminate\Support\ServiceProvider;
use Pterodactyl\Contracts\Extensions\HashidsInterface;

class HashidsServiceProvider extends ServiceProvider
{
    /**
     * Register the ability to use Hashids.
     */
    public function register(): void
    {
        $this->app->singleton(HashidsInterface::class, function () {
            /** @var \Illuminate\Contracts\Config\Repository $config */
            $config = $this->app['config'];

            return new Hashids(
                $config->get('hashids.salt', ''),
                $config->get('hashids.length', 0),
                $config->get('hashids.alphabet', 'abcdefghijkmlnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890')
            );
        });

        $this->app->alias(HashidsInterface::class, 'hashids');
    }
}
/app/app/Providers # 
```

**Comment by KenRen98** [comment]
没事了，手动在/app/var/.env里面加入了salt的env设置后，解决了该问题

```
# .env
HASHIDS_SALT=YourSaltStringHere
HASHIDS_LENGTH=8
HASHIDS_ALPHABET=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890
```

```
# PHP artisan重载指令
php artisan config:clear
php artisan config:cache
```



本来以为这里PHP code的意思是默认设置为‘’
```
# PHP provider
/app/app # cd Providers/
/app/app/Providers # cat HashidsServiceProvider.php 
<?php

namespace Pterodactyl\Providers;

use Pterodactyl\Extensions\Hashids;
use Illuminate\Support\ServiceProvider;
use Pterodactyl\Contracts\Extensions\HashidsInterface;

class HashidsServiceProvider extends ServiceProvider
{
    /**
     * Register the ability to use Hashids.
     */
    public function register(): void
    {
        $this->app->singleton(HashidsInterface::class, function () {
            /** @var \Illuminate\Contracts\Config\Repository $config */
            $config = $this->app['config'];

            return new Hashids(
                $config->get('hashids.salt', ''),
                $config->get('hashids.length', 0),
                $config->get('hashids.alphabet', 'abcdefghijkmlnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890')
            );
        });

        $this->app->alias(HashidsInterface::class, 'hashids');
    }
}
/app/app/Providers # 
```
