### ISSUE TITLE
创建支援 `linux/s390x` 架构的 Docker Image

### ISSUE THREAD

**Issue by ench233** [pterodactyl-china/panel#61]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

软件包不支援 `linux/s390x` 架构

### Describe the solution you'd like.

和其它 Image 一样用

**Comment by vlssu** [comment]
已支持 `linux/s390x`，如果想提前使用，可以自行替换拉取镜像 `ghcr.io/pterodactyl-china/panel:1.0-develop` 国内代理为  `ghcr.dockerproxy.com/pterodactyl-china/panel:1.0-develop` ，详细可以见 https://github.com/pterodactyl-china/panel/pkgs/container/panel/200566271?tag=1.0-develop

**Comment by ench233** [comment]
感谢如此及时且有效的修改，议题将会关闭。
